trigger:
    - none
    
variables:
    major: 2
    minor: 4
name: $(major).$(minor).$(Rev:r)

stages:
- stage: 'Integration_Build'
  displayName: 'Build Application'

  jobs:
    - job: 'Build'
      displayName: 'Build job'
      pool:
        vmImage: 'windows-latest'
      variables:
      - group: onion8-from-scratch-tdd
      steps:
      - task: UseDotNet@2
        displayName: 'Install SDK 8.0.100'
        inputs:
          packageType: 'sdk'
          version: '8.0.100'
      - task: UseDotNet@2
        inputs:
          packageType: 'runtime'
          version: '6.0.0'
      - task: UseDotNet@2
        inputs:
          packageType: 'runtime'
          version: '8.0.0'
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            [System.Environment]::SetEnvironmentVariable('Version','$(Build.BuildNumber)')
            echo $env:Version
            echo $(Build.BuildNumber)

      - task: PowerShell@2
        displayName: Build.ps1
        inputs:
          targetType: filePath
          filePath: ./build.ps1
          arguments: '; CIBuild'
      - task: PublishTestResults@2
        displayName: 'Publish Test Results ./build/test/*.trx'
        inputs:
          testResultsFormat: VSTest
          testResultsFiles: 'build/test/**/*.trx'
          mergeTestResults: true
          testRunTitle: 'CI Tests'
        continueOnError: true
        condition: succeededOrFailed()
      - task: PublishCodeCoverageResults@1
        displayName: 'Publish code coverage UnitTests'
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/build/test/**/In/**/coverage.cobertura.xml'
      
      - task: NuGetCommand@2
        inputs:
          command: 'push'
          packagesToPush: '.\build\*.nupkg'
          publishVstsFeed: '$(AzureFeedName)'

    - job: 'DockerBuildandPush'
      pool:
        vmImage: 'ubuntu-latest'
      variables:
        - group: onion8-from-scratch-tdd
      dependsOn: Build
 
      steps:
      - task: DownloadPackage@1
        displayName: 'Download UI Package'
        inputs:
          packageType: 'nuget'
          feed: '$(AzureFeedName)'
          view: 'Local'
          definition: 'ChurchBulletin.UI'
          version: '$(Build.BuildNumber)'
          downloadPath: '$(System.DefaultWorkingDirectory)/built'
          extract: true

      - task: Docker@2
        inputs:
          containerRegistry: 'onion8-from-scratch-docker-sc'
          repository: 'ChurchBulletin.UI'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: |
            $(Build.BuildNumber)

# Deploying to TDD
- stage: 'TDD'
  displayName: 'TDD'
  jobs:
    - deployment: 'DeployToTDD'
      pool:
        vmImage: 'windows-latest'
      variables:
      - group: onion8-from-scratch-tdd
      - name: branch
        value: $[coalesce(variables['system.pullRequest.sourceBranch'], variables['build.sourceBranch'])]
      - name: TDDResourceGroup
        value: '$(ResourceGroupName)-$(Build.BuildNumber)'
      - name: Environment
        value: 'tdd'
      - name: containerAppLogAnalyticsName
        value: 'tdd-Log-Analytics'
      - name: appInsightsName
        value: 'onion8-clean-tdd-insights'
      - name: AspnetcoreEnvironment
        value: $(AspnetcoreEnvironmentTest)

      environment: 'TDD'
      strategy:
        runOnce:
          deploy:
            steps:
            
            - template: .\deploy-env.yml

- stage: 'UAT'
  displayName: 'UAT'
  # dependsOn: TDD
  jobs:
    - deployment: 'DeployToUAT'
      pool:
        vmImage: 'windows-latest'
      variables:
      - group: onion8-from-scratch-uat
      - name: branch
        value: $[coalesce(variables['system.pullRequest.sourceBranch'], variables['build.sourceBranch'])]
      - name: TDDResourceGroup
        value: '$(ResourceGroupName)'
      - name: Environment
        value: 'uat'
      - name: AppInsightsConnectionString
        value: '$(AppInsightsConnectionStringUAT)'
      - name: appInsightsName
        value: 'onion-architecture-maui-azure-dotnet-8-UAT-Insights'
      - name: containerAppLogAnalyticsName
        value: 'UAT-Log-Analytics'
      environment: 'UAT'
      strategy:
        runOnce:
          deploy:
            steps:
            
            - template: .\deploy-env.yml

- stage: 'Production'
  displayName: 'Prod'
  jobs:
    - deployment: 'DeployToProd'
      pool:
        vmImage: 'windows-latest'
      variables:
      - group: onion8-from-scratch-prod
      - name: branch
        value: $[coalesce(variables['system.pullRequest.sourceBranch'], variables['build.sourceBranch'])]
      - name: TDDResourceGroup
        value: '$(ResourceGroupName)'
      - name: Environment
        value: 'prod'
      - name: AppInsightsConnectionString
        value: '$(AppInsightsConnectionStringProd)'
      - name: appInsightsName
        value: 'onion-architecture-maui-azure-dotnet-8-Prod-Insights'
      - name: containerAppLogAnalyticsName
        value: 'Prod-Log-Analytics'
      environment: 'Prod'
      strategy:
        runOnce:
          deploy:
            steps:
            
            - template: .\deploy-env.yml